version: '3.9'
services:
  backend:
    image: backendpyreact
    build:
      context: ./django
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  frontend:
    image: frontendpyreact
    build:
      context: ./vite-project
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend